spring:
#  datasource:
#    url: "jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS KEEPUP_DB;"
#    driver-class-name: org.h2.Driver
#    driverClassName: org.h2.Driver
#    username: sa
#    password: ""
#    database-platform: org.hibernate.dialect.H2Dialect
#  r2dbc:
#    url: "r2dbc:h2:mem://./test;MODE=PostgreSQL;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;"
#    username: "sa"
#    password: ""
#  liquibase:
#    enabled: true
#    change-log: "classpath:db/changelog/db.changelog-master.yaml"
