spring:
  profiles.active: dev,security,h2
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    root: INFO
    io.keepup.cms: INFO

keepup:
  paths:
    static: /Users/fedkapot/IdeaProjects/keepup-application/resources/
  plugins:
    catalog:
      enabled: true
    adminui:
      enabled: true
  security:
    csrf-enabled: false