spring:
  profiles.active: dev,postgres,security,redis
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    root: INFO
    io.keepup.cms.projects.rest: DEBUG
keepup:
  paths:
    static: /app/static
  plugins:
    catalog:
      enabled: true