name: Java CI with Gradle

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: 
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build -PnexusUser=${{ secrets.NEXUS_USER }} -PnexusPassword=${{ secrets.NEXUS_PASSWORD }}
      env:
        MAVEN_USERNAME: ${{ secrets.NEXUS_USER }}
        MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
    - name: Generate changelog
      run: ./gradlew generateGitChangelogInlineTemplate
    - name: JaCoCo
      run: ./gradlew codeCoverageReport
    - name: Coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - uses: actions/upload-artifact@v1
      with:
        name: keepup-base-app-1.0.jar
        path: build/libs/

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/download-artifact@v1
        with:
          name: keepup-base-app-1.0.jar
          path: build/libs/

      - name: Download math result for job 1
        uses: actions/download-artifact@v2
        with:
          name: keepup-base-app-1.0.jar
          path: build/libs/
      - shell: bash
        run: |
          ls -la build/libs

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          # todo set tag
          tags: fsergeev/keepup-base-app:healthcheck-01
          build-args: JAR_FILE=build/libs/keepup-base-app-1.0.jar
